server:
  port: 6001
  servlet:
    context-path: /
spring:
  resources:
    static-locations: classpath:static,file:D:\uploadFile\ueimage\    #用于映射上传文件目录
  application:
    name: xingHe-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sa123
    url: jdbc:mysql://localhost:3306/ElaneWhal_xh?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    type: com.zaxxer.hikari.HikariDataSource
    # hikari 连接池  https://blog.csdn.net/X5fnncxzq4/article/details/80649679
    #https://github.com/brettwooldridge/HikariCP#checkered_flag-jmh-benchmarks
    hikari:
      # 自动提交
      auto-commit: true
      connection-test-query: SELECT 1
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      # 生产环境 connect-time 10 s
      connection-timeout: 9000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout 7200s 参数（# 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->  ） -->
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 15
      # 最小连接数
      minimum-idle: 10
      # 连接池名字
      pool-name: DemoHikariCP
  # Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）如果有可以设置 password: redis123
    timeout: 10000 # 连接超时时间（毫秒）
    block-when-exhausted: true # 连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
    jedis:
      pool:
        max-active: 500 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 200 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    mybatis-plus:
      # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
      #    type-aliases-package: com.elane.*.entity.*
      # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
      #type-aliases-super-type: java.lang.Object
      #    mapper-locations: classpath:mapper/**/*Mapper.xml
      configuration:
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        # 驼峰下划线转换
        map-underscore-to-camel-case: true
        # 配置的缓存的全局开关
        cache-enabled: true
        # 延时加载的开关
        lazy-loading-enabled: true
        # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
        multiple-result-sets-enabled: true
        use-generated-keys: true
        default-statement-timeout: 60
        default-fetch-size: 100

##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800
logging:
  level:
    com:
      example:
        demo:
          dao: debug

# savefilePath: C:\Users\elane\Desktop\xh\xingHe\xingHe-web\src\main\resources\static\uploadFile\ueimage\
savefilePath: D:\static\uploadFile\ueimage\
company: 天可生物制药